---
output: 
  pdf_document:
      template: template.tex
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\begin{center}
{\Large \textsc{PSTAT 115: Introduction to Bayesian Data Analysis}}
\end{center}
\begin{center}
Fall 2022
\end{center}

\begin{center}
\rule{6in}{0.4pt}
\begin{minipage}[t]{.75\textwidth}
\begin{tabular}{llcccll}
\textbf{Instructor:} & Rodrigo Targino & & &  & \textbf{Time:} & T/R 8:00-9:15\\
\textbf{Email:} &
                  \href{mailto:rodrigotargino@ucsb.edu}{rodrigotargino@ucsb.edu}
                                        & & & &  & 
\end{tabular}
\end{minipage}
\rule{6in}{0.4pt}
\end{center}
\vspace{.5cm}
\setlength{\unitlength}{1in}
\renewcommand{\arraystretch}{2}


\noindent\textbf{Course Pages:}
\begin{itemize}
\item Location: \href{https://www.google.com/maps/search/?api=1&query=ucsb%20HSSB}{HSSB 1174}
\item Gauchospace: \href{https://gauchospace.ucsb.edu/courses/course/view.php?id=33131}{link}
\item Nectir: \href{https://app.nectir.io/group/ucsb/pstat-115-f22}{link}. We ask that when you have a question about the class that might be relevant to other students, post it on Nectir instead of emailing us. That way, all the staff can be on the same page and everyone can benefit from the response. Click on the Nectir link on Gaucho to be automatically added to the class channel. If you don't have an account already, to please make one at \url{ucsb.nectir.io}.
\item JupyterHub: \href{https://pstat115.lsit.ucsb.edu/}{link}. All your work should be completed here.
\item GradeScope: \href{https://www.gradescope.com/courses/445614}{link}. Weekly homework assignments are a required part of the course. You are allowed to work with one partner. When submiting to GradeScope, you must include your partners name (link the submission), so that you both get full credit!
\item Use this \href{https://tinyurl.com/2hpr9mpj}{link} to sync new assignments and labs.
\begin{itemize}
\item {\color{red} Bookmark this link, you will use it a lot!}
\end{itemize}

\end{itemize}



\vskip.15in
\noindent\textbf{Office Hours:}

\noindent Professor Targino \url{rodrigotargino@ucsb.edu}: Office Hours, Fridays 3-4pm

\noindent Lauren Hughes [TA] \url{laurenhughes@ucsb.edu}: Office Hours, Mondays 10-11am

\noindent Yaqiao (Darcy) Wang [TA] \url{darcywang@ucsb.edu}: Office Hours, Wednesdays 2:30 - 4:30pm

\noindent Cyril Wang [ULA] \url{cyrilwang@ucsb.edu}: Office Hours, Tuesdays 10am-12pm (on Zoom);  Fridays 10am-12pm (in-person)

\vskip.15in
\noindent\textbf{Course Texts} 

\begin{itemize}
\item \textbf{Required:} Alicia A. Johnson, Miles Q. Ott, Mine Dogucu \textit{Bayes Rules} \url{https://www.bayesrulesbook.com/}
\item Optional: Peter Hoff {\textit{A First Course in Bayesian
      Statistical Methods}};  \url{https://www.springer.com/us/book/9780387922997}).
\item Optional: Jim Albert {\textit{Bayesian Computation with R}};
  \url{https://www.springer.com/us/book/9780387922973}).
  \item Optional: Richard McElreath {\textit{Statistical Rethinking}};  \url{https://xcelab.net/rm/statistical-rethinking/}).  
  \item Optional: Andrew Gelman, John Carlin et al. {\textit{Bayesian
        Data Analysis}};  \url{http://www.stat.columbia.edu/~gelman/book/}).
\end{itemize} 

\vskip.15in
\noindent\textbf{Objectives:} 

\vspace{1em}
At the end of the course, a successful student will be able to:
\begin{itemize}
\item build and refine statistical models using the Bayesian paradigm
\item utilize Monte Carlo methods for statistical inference
\end{itemize}

\vskip.15in
\noindent\textbf{Prerequisites:}
PSTAT 120 A-B (probability and math-stat) and 126 (regression). Familiarity with R is required.

\vspace*{.15in}

\noindent \textbf{Tentative Course Topics:}
\begin{center}
\begin{minipage}{5in}
\begin{flushleft}
{\color{darkgreen}{\Rectangle}} ~ Review of frequentist inference\\
{\color{darkgreen}{\Rectangle}} ~ One parameter models\\
{\color{darkgreen}{\Rectangle}} ~ Monte Carlo computation\\
{\color{darkgreen}{\Rectangle}} ~ The normal model\\
{\color{darkgreen}{\Rectangle}} ~ Markov chain Monte Carlo\\
{\color{darkgreen}{\Rectangle}} ~ Hierarchical models\\
{\color{darkgreen}{\Rectangle}} ~ An introduction to probabilistic programming\\
\end{flushleft}
\end{minipage}
\end{center}

<!-- \pagebreak -->

\vspace*{.15in}
\noindent\textbf{Grading Policy:}
\begin{itemize}
\item Homework (35\%).
  \begin{itemize}
    \item There will be approximately 6 homeworks, due roughly every
     week on Sundays at midnight.
      \item You are allowed to work with a partner. You need only turn in one homework per pair. Homework solutions must be done in RMarkdown and turned in on Gradescope.  Each homework assignment will be given as a template that you should work from.
\item All code must be written to be reproducible in Rmarkdown
\item  All derivations can be done in any format of your choosing (latex, written by hand) but must be legible and \emph{must be incorporated into your final pdf}.
\item  All files must be zipped together and submitted to Gradescope
\item  Ask a TA \emph{early} if you have problems regarding submissions. 
  \item Homework not submitted online before the deadline will
  be considered late (10 point deduction). 24 hours after the deadline
  homework will not be accepted and no credit will be awarded. Do not
  wait until the night before it is due to start working!
  \end{itemize}

\item Midterm exam (20\%). \textbf{Take home, due October 27, 2022} . 

\item Quizzes + Participation (15\%)
  \begin{itemize}
    \item Approximately 5 in quizzes (online), lowest dropped
    \item There is no make-up for missed quizzes.
    \item Section attendance is required and essential.  Your
    attendance will be noted.  
  \end{itemize}
\item Final exam (30\%). \textbf{Take home, due Monday December 8, 2022}
\end{itemize}

\noindent{\textbf{Homeworks:}}

\begin{itemize}
\item  All files will be submitted electronically via Gradescope
\item  Submit a zip file containing:
  \begin{enumerate}
    \item R markdown code (.Rmd file, template provided)\\
    \item Any additional files as needed\\
    \item Generated PDF file
  \end{enumerate}
\end{itemize}
\vskip.15in
\newpage
\noindent\textbf{Important Dates:}
\begin{center} \begin{minipage}{3.8in}
    \begin{flushleft}
Midterm \dotfill ~ October 27, 2022 (take home)\\
Final Exam \dotfill ~ December 8, 2022 (take home)\\
\end{flushleft}
\end{minipage}
\end{center}

\vskip.15in
\noindent\textbf{Course Policies:}  

\begin{itemize}
\item Learning Cooperatively
\begin{itemize}
\item We encourage you to discuss all of the course activities with your friends and classmates as you are working on them. 
\item You will definitely learn more in this class if you work with others than if you do not. Ask questions, answer questions, and share ideas liberally.
\end{itemize}
\item Academic Honesty
\begin{itemize} 
\item Cooperation has a limit. 
\item You should not share your code or answers directly with other students. 
\item Doing so doesn’t help them; it just sets them up for trouble on exams. 
\item Feel free to discuss the problems with others beforehand, but not the solutions.
\item Please complete your own work and keep it to yourself. 
\item The exception to this rule is that you can share everything related to a project with your project partner and turn in one project between you.
\item Penalties for cheating are severe — they range from a zero grade for the assignment up to dismissal from the University, for a second offense.
\item Rather than copying someone else’s work, ask for help. You are not alone in this course! We are here to help you succeed. If you invest the time to learn the material and complete the projects, you won’t need to copy any answers.
\end{itemize}
\item Copyright of Course Materials
\begin{itemize}
\item Most of the material for this course was prepared by Professor Alex Franks.
\item The lectures and course materials, including PowerPoint presentations, tests, outlines, and similar materials, are protected by U.S. copyright law and by University policy. 
\item I am the exclusive owner of the copyright in those materials I create. You may take notes and make copies of course materials for your own use. 
\item You may also share those materials with another student who is enrolled in or auditing this course.
\item You may not reproduce, distribute or display (post/upload) lecture notes or recordings or course materials in any other way — whether or not a fee is charged — without my express prior written consent. You also may not allow others to do so.
\item If you do so, you may be subject to student conduct proceedings under the UC Santa Barbara Student Code of Conduct.
\item Similarly, you own the copyright in your original papers and exam essays. If I am interested in posting your answers or papers on the course web site, I will ask for your written permission.

\end{itemize}
\end{itemize}